### ISSUE TITLE
⚠️[THIS IS NOT RELATED TO THIS REPO BUT I DON'T KNOW HOW TO REACH YOU]

### ISSUE THREAD

**Issue by dreamwhite** [radianttap/TestiOS#1]
As per title I didn't find a method to reach you, until I found your github repository. I know that this isn't the right place where contact you but I don't have any method to do it. Open a dedicated repository to your website as I need to suggest some fixes inside the USB guide, for example, by telling how to create a USB ssdt starting from the vanilla one etc...
Sorry again 😅

**Comment by radianttap** [comment]
I assume you mean [about this post](https://aplus.rs/2020/usb-mapping-how/)? That blog is not under any kind of repo and I'm looking for time to switch to a different engine.

I'll see to extract just the hackintosh parts and add them somewhere here.

**Comment by dreamwhite** [comment]
Yeah, opt for Gitbook for example :)

**Comment by radianttap** [comment]
I already have these written as Markdown files, so just linked them up in the README. 

https://github.com/radianttap/ryzentosh
